### ISSUE TITLE
Update web page?

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/zulip-archive#3]
@dcherian -- Would it be possible to run the main workflow to update the github page? It's been almost three years since the last update. (I'm happy to be an admin of this repo and figure out how to run it myself if that would be easier.)

**Comment by dcherian** [comment]
last I tried, the action doesn't really work; also i seem to have lost permissions here :/ might have to follow up with NRIT

**Comment by mnlevy1981** [comment]
Thanks for trying! I'll open an issue ticket with our help desk to see about getting elevated here, and then might spend some time poking around to try to fix the action.

**Comment by mnlevy1981** [comment]
Manually ran `zulip/zulip-archive` on my laptop and pushed changes; removed the github action and (for now) will just occasionally update the page manually now that [I know how to](https://github.com/NCAR/zulip-archive/commit/23e30e7e7ac4875735cf0fd6e25f517e6ae16625)
